'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.5456
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  强类型资源类，用于查找本地化字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MALS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  为使用此强类型资源类的所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property alloff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alloff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property allon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("allon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property company1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property company2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property esc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("esc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property esc1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("esc1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property esc2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("esc2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gray_lamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gray_lamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property green_lamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_lamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QQ截图20150429110815() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QQ截图20150429110815", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QQ截图20150612182608() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QQ截图20150612182608", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QQ截图20150805081908() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QQ截图20150805081908", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QQ截图20150805081908_副本() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QQ截图20150805081908_副本", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QQ截图20181102112030() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QQ截图20181102112030", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ray_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ray_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property red_lamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_lamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redb1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redb1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property white_lamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("white_lamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xy1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xy1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 手() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("手", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 放大() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("放大", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 标题背景() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("标题背景", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 消音() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("消音", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 缩小() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("缩小", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 背景() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("背景", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 退出() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("退出", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 适合窗口() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("适合窗口", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 选择工具() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("选择工具", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
